import type { Metadata } from "next";
import localFont from "next/font/local";
import { Inter as FontSans } from "next/font/google";
import { Source_Serif_4 as FontSerif } from "next/font/google";

import AppContextProvider from "@/components/providers/app-provider";
import "@/styles/globals.css";

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

const fontSerif = FontSerif({
  subsets: ["latin"],
  variable: "--font-serif",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AppContextProvider>
        <body
          className={`${fontSans.variable} ${geistMono.variable}  ${fontSerif.variable} font-sans antialiased bg-background`}
        >
          {children}
        </body>
      </AppContextProvider>
    </html>
  );
}
